-- TB_USR_USER
CREATE TABLE "TB_USR_USER"
(
    ID bigint NOT NULL,
    NAME varchar(80) NOT NULL,
    EMAIL varchar(100),
    USERNAME varchar(80) NOT NULL,
    PASSWORD varchar(80) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE SEQUENCE "SQ_USER" AS INT INCREMENT BY 1 START WITH 500 NO CYCLE;

-- TB_ROL_ROLE
CREATE TABLE "TB_ROL_ROLE"
(
    ID bigint NOT NULL,
    NAME varchar(80) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE SEQUENCE "SQ_ROLE" AS INT INCREMENT BY 1 START WITH 500 NO CYCLE;

-- TB_PRM_PERMISSION
CREATE TABLE "TB_PRM_PERMISSION"
(
    ID bigint NOT NULL,
    NAME varchar(80) NOT NULL,
    METHOD varchar(80) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE SEQUENCE "SQ_PERMISSION" AS INT INCREMENT BY 1 START WITH 500 NO CYCLE;

-- TB_RPM_ROLE_PERMISSION
CREATE TABLE "TB_RPM_ROLE_PERMISSION"
(
    ROLE_ID bigint NOT NULL,
    PERMISSION_ID bigint NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);

CREATE TABLE "TB_URL_USER_ROLE"
(
    USER_ID bigint NOT NULL,
    ROLE_ID bigint NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID)
);

INSERT INTO "TB_ROL_ROLE" (ID,NAME) VALUES (1,'ROLE_ADMIN');
INSERT INTO "TB_ROL_ROLE" (ID,NAME) VALUES (2,'ROLE_USER');

-- ROLES
--- > Permissões do serviço usuário
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (10,'v1/users', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (11,'v1/users/{id}', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (12,'v1/users/{name}', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (13,'v1/users', 'POST');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (14,'v1/users', 'PUT');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (15,'v1/users/{id}', 'DELETE');

--- > Permissões do serviço perfil
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (30,'v1/roles', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (31,'v1/roles/{id}', 'GET');

--- > Permissões do serviço permissao
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (50,'v1/permissions', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (51,'v1/permissions/{id}', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (52,'v1/permissions/{id}', 'DELETE');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (53,'v1/permissions', 'POST');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (54,'v1/permissions', 'PUT');

--> Perfil x Permissão
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (70,'v1/roles-permissions', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (71,'v1/roles-permissions/roles/{id}', 'GET');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (72,'v1/roles-permissions/roles/{idRole}/permissions/{idPermission}', 'POST');
INSERT INTO "TB_PRM_PERMISSION" (ID,NAME,METHOD) VALUES (73,'v1/roles-permissions/roles/{idRole}/permissions/{idPermission}', 'DELETE');

-- Admin (Associando tudo ao Perfil ADMIN)
INSERT INTO "TB_RPM_ROLE_PERMISSION" (ROLE_ID,PERMISSION_ID)
SELECT 1, ID FROM "TB_PRM_PERMISSION";

INSERT INTO "TB_USR_USER" (ID, NAME, EMAIL, USERNAME, PASSWORD) VALUES
(1, 'Administrador', 'admin@admin', 'admin', '$2a$10$AClqa6pS99KTaT2QpbYdvuVP1yf3QOSBeHvzdjaphp5A3GY91yvEO');

INSERT INTO "TB_URL_USER_ROLE" (USER_ID, ROLE_ID) VALUES
(1, 1);